#############################################################################
# Makefile for building: Don_king_kong.app/Contents/MacOS/Don_king_kong
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  ../Don_king_kong/Don_king_kong.pro
# Template: app
# Command: /Users/joachimferrari/Applications/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile ../Don_king_kong/Don_king_kong.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I../Don_king_kong -I. -I../Applications/5.7/clang_64/lib/QtWidgets.framework/Headers -I../Applications/5.7/clang_64/lib/QtGui.framework/Headers -I../Applications/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../Applications/5.7/clang_64/mkspecs/macx-clang -F/Users/joachimferrari/Applications/5.7/clang_64/lib
QMAKE         = /Users/joachimferrari/Applications/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Don_king_kong1.0.0
DISTDIR = /Users/joachimferrari/build-Don_king_kong-Desktop_Qt_5_7_0_clang_64bit-Debug/.tmp/Don_king_kong1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/joachimferrari/Applications/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/joachimferrari/Applications/5.7/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Don_king_kong/main.cpp \
		../Don_king_kong/view.cpp \
		../Don_king_kong/model.cpp \
		../Don_king_kong/control.cpp moc_view.cpp
OBJECTS       = main.o \
		view.o \
		model.o \
		control.o \
		moc_view.o
DIST          = ../Applications/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../Applications/5.7/clang_64/mkspecs/qdevice.pri \
		../Applications/5.7/clang_64/mkspecs/features/device_config.prf \
		../Applications/5.7/clang_64/mkspecs/common/unix.conf \
		../Applications/5.7/clang_64/mkspecs/common/mac.conf \
		../Applications/5.7/clang_64/mkspecs/common/macx.conf \
		../Applications/5.7/clang_64/mkspecs/common/sanitize.conf \
		../Applications/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../Applications/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Applications/5.7/clang_64/mkspecs/common/clang.conf \
		../Applications/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../Applications/5.7/clang_64/mkspecs/qconfig.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Applications/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../Applications/5.7/clang_64/mkspecs/features/qt_config.prf \
		../Applications/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../Applications/5.7/clang_64/mkspecs/features/spec_post.prf \
		../Applications/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../Applications/5.7/clang_64/mkspecs/features/default_pre.prf \
		../Applications/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../Applications/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../Applications/5.7/clang_64/mkspecs/features/default_post.prf \
		../Applications/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../Applications/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../Applications/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../Applications/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../Applications/5.7/clang_64/mkspecs/features/warn_on.prf \
		../Applications/5.7/clang_64/mkspecs/features/qt.prf \
		../Applications/5.7/clang_64/mkspecs/features/resources.prf \
		../Applications/5.7/clang_64/mkspecs/features/moc.prf \
		../Applications/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../Applications/5.7/clang_64/mkspecs/features/uic.prf \
		../Applications/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../Applications/5.7/clang_64/mkspecs/features/file_copies.prf \
		../Applications/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../Applications/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../Applications/5.7/clang_64/mkspecs/features/exceptions.prf \
		../Applications/5.7/clang_64/mkspecs/features/yacc.prf \
		../Applications/5.7/clang_64/mkspecs/features/lex.prf \
		../Don_king_kong/Don_king_kong.pro ../Don_king_kong/view.h \
		../Don_king_kong/model.h \
		../Don_king_kong/control.h ../Don_king_kong/main.cpp \
		../Don_king_kong/view.cpp \
		../Don_king_kong/model.cpp \
		../Don_king_kong/control.cpp
QMAKE_TARGET  = Don_king_kong
DESTDIR       = 
TARGET        = Don_king_kong.app/Contents/MacOS/Don_king_kong


first: all
####### Build rules

$(TARGET): ui_view.h $(OBJECTS)  
	@test -d Don_king_kong.app/Contents/MacOS/ || mkdir -p Don_king_kong.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Don_king_kong/Don_king_kong.pro ../Applications/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../Applications/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../Applications/5.7/clang_64/mkspecs/qdevice.pri \
		../Applications/5.7/clang_64/mkspecs/features/device_config.prf \
		../Applications/5.7/clang_64/mkspecs/common/unix.conf \
		../Applications/5.7/clang_64/mkspecs/common/mac.conf \
		../Applications/5.7/clang_64/mkspecs/common/macx.conf \
		../Applications/5.7/clang_64/mkspecs/common/sanitize.conf \
		../Applications/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../Applications/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Applications/5.7/clang_64/mkspecs/common/clang.conf \
		../Applications/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../Applications/5.7/clang_64/mkspecs/qconfig.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Applications/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../Applications/5.7/clang_64/mkspecs/features/qt_config.prf \
		../Applications/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../Applications/5.7/clang_64/mkspecs/features/spec_post.prf \
		../Applications/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../Applications/5.7/clang_64/mkspecs/features/default_pre.prf \
		../Applications/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../Applications/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../Applications/5.7/clang_64/mkspecs/features/default_post.prf \
		../Applications/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../Applications/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../Applications/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../Applications/5.7/clang_64/mkspecs/features/qml_debug.prf \
		../Applications/5.7/clang_64/mkspecs/features/warn_on.prf \
		../Applications/5.7/clang_64/mkspecs/features/qt.prf \
		../Applications/5.7/clang_64/mkspecs/features/resources.prf \
		../Applications/5.7/clang_64/mkspecs/features/moc.prf \
		../Applications/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../Applications/5.7/clang_64/mkspecs/features/uic.prf \
		../Applications/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../Applications/5.7/clang_64/mkspecs/features/file_copies.prf \
		../Applications/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../Applications/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../Applications/5.7/clang_64/mkspecs/features/exceptions.prf \
		../Applications/5.7/clang_64/mkspecs/features/yacc.prf \
		../Applications/5.7/clang_64/mkspecs/features/lex.prf \
		../Don_king_kong/Don_king_kong.pro \
		../Applications/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../Applications/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../Applications/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile ../Don_king_kong/Don_king_kong.pro
../Applications/5.7/clang_64/mkspecs/features/spec_pre.prf:
../Applications/5.7/clang_64/mkspecs/qdevice.pri:
../Applications/5.7/clang_64/mkspecs/features/device_config.prf:
../Applications/5.7/clang_64/mkspecs/common/unix.conf:
../Applications/5.7/clang_64/mkspecs/common/mac.conf:
../Applications/5.7/clang_64/mkspecs/common/macx.conf:
../Applications/5.7/clang_64/mkspecs/common/sanitize.conf:
../Applications/5.7/clang_64/mkspecs/common/gcc-base.conf:
../Applications/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../Applications/5.7/clang_64/mkspecs/common/clang.conf:
../Applications/5.7/clang_64/mkspecs/common/clang-mac.conf:
../Applications/5.7/clang_64/mkspecs/qconfig.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Applications/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Applications/5.7/clang_64/mkspecs/features/qt_functions.prf:
../Applications/5.7/clang_64/mkspecs/features/qt_config.prf:
../Applications/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../Applications/5.7/clang_64/mkspecs/features/spec_post.prf:
../Applications/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../Applications/5.7/clang_64/mkspecs/features/default_pre.prf:
../Applications/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../Applications/5.7/clang_64/mkspecs/features/resolve_config.prf:
../Applications/5.7/clang_64/mkspecs/features/default_post.prf:
../Applications/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../Applications/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../Applications/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../Applications/5.7/clang_64/mkspecs/features/qml_debug.prf:
../Applications/5.7/clang_64/mkspecs/features/warn_on.prf:
../Applications/5.7/clang_64/mkspecs/features/qt.prf:
../Applications/5.7/clang_64/mkspecs/features/resources.prf:
../Applications/5.7/clang_64/mkspecs/features/moc.prf:
../Applications/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../Applications/5.7/clang_64/mkspecs/features/uic.prf:
../Applications/5.7/clang_64/mkspecs/features/unix/thread.prf:
../Applications/5.7/clang_64/mkspecs/features/file_copies.prf:
../Applications/5.7/clang_64/mkspecs/features/mac/rez.prf:
../Applications/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../Applications/5.7/clang_64/mkspecs/features/exceptions.prf:
../Applications/5.7/clang_64/mkspecs/features/yacc.prf:
../Applications/5.7/clang_64/mkspecs/features/lex.prf:
../Don_king_kong/Don_king_kong.pro:
../Applications/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../Applications/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../Applications/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug -o Makefile ../Don_king_kong/Don_king_kong.pro

qmake_all: FORCE

Don_king_kong.app/Contents/PkgInfo: 
	@test -d Don_king_kong.app/Contents || mkdir -p Don_king_kong.app/Contents
	@$(DEL_FILE) Don_king_kong.app/Contents/PkgInfo
	@echo "APPL????" > Don_king_kong.app/Contents/PkgInfo
Don_king_kong.app/Contents/Resources/empty.lproj: 
	@test -d Don_king_kong.app/Contents/Resources || mkdir -p Don_king_kong.app/Contents/Resources
	@touch Don_king_kong.app/Contents/Resources/empty.lproj
	
Don_king_kong.app/Contents/Info.plist: 
	@test -d Don_king_kong.app/Contents || mkdir -p Don_king_kong.app/Contents
	@$(DEL_FILE) Don_king_kong.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,jo.Don-king-kong,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Don_king_kong,g" -e "s,@LIBRARY@,Don_king_kong,g" -e "s,@TYPEINFO@,????,g" ../Applications/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >Don_king_kong.app/Contents/Info.plist

all: Makefile \
		Don_king_kong.app/Contents/PkgInfo \
		Don_king_kong.app/Contents/Resources/empty.lproj \
		Don_king_kong.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Don_king_kong/view.h ../Don_king_kong/model.h ../Don_king_kong/control.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Don_king_kong/main.cpp ../Don_king_kong/view.cpp ../Don_king_kong/model.cpp ../Don_king_kong/control.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Don_king_kong/view.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Don_king_kong.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_view.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_view.cpp
moc_view.cpp: ../Applications/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Applications/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Don_king_kong/view.h \
		../Applications/5.7/clang_64/bin/moc
	/Users/joachimferrari/Applications/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/joachimferrari/Applications/5.7/clang_64/mkspecs/macx-clang -I/Users/joachimferrari/Don_king_kong -I/Users/joachimferrari/Applications/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/joachimferrari/Applications/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/joachimferrari/Applications/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/7.3.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I'/System/Library/Frameworks (framework directory)' -I'/Library/Frameworks (framework directory)' -F/Users/joachimferrari/Applications/5.7/clang_64/lib ../Don_king_kong/view.h -o moc_view.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_view.h
compiler_uic_clean:
	-$(DEL_FILE) ui_view.h
ui_view.h: ../Don_king_kong/view.ui \
		../Applications/5.7/clang_64/bin/uic
	/Users/joachimferrari/Applications/5.7/clang_64/bin/uic ../Don_king_kong/view.ui -o ui_view.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../Don_king_kong/main.cpp ../Don_king_kong/view.h \
		../Applications/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Applications/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../Applications/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../Applications/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Don_king_kong/main.cpp

view.o: ../Don_king_kong/view.cpp ../Don_king_kong/view.h \
		../Applications/5.7/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../Applications/5.7/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o ../Don_king_kong/view.cpp

model.o: ../Don_king_kong/model.cpp ../Don_king_kong/model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o model.o ../Don_king_kong/model.cpp

control.o: ../Don_king_kong/control.cpp ../Don_king_kong/control.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o control.o ../Don_king_kong/control.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

